### ISSUE TITLE
error al subir datos de campaña

### ISSUE THREAD

**Issue by TadeoArmenta** [IssabelFoundation/callcenter#1]
Este es el error que muestra la consola js de chrome, al momento de presionar el boton de guardar

```
index.php?menu=campaign_out&action=load_contacts&id_campaign=2:1439 Uncaught ReferenceError: enviar_datos is not defined
    at HTMLInputElement.onclick (index.php?menu=campaign_out&action=load_contacts&id_campaign=2:1439)
```

al parecer falta el js con la funcion "enviar_datos" en el forulario para subir un .csv con los datos de la campaña
el archivo load_contacts.tpl contiene el formulario para cargar el csv, pero carece de la funcion de enviar datos

**Comment by asternic** [comment]
Hola, Si bien tienes ese error en consola, la importación CSV se realiza correctamente (al menos en mis pruebas). Seguro que no te está realizando la importación? Verificaste la tabla calls de la base de datos call_center ? Voy a revisar ese error, pero aparentemente *no* afecta a que se realice la importación, por lo que en ese caso podría ser ignorado.

Saludos,

**Comment by asternic** [comment]
He confirmado que es un error simplemente cosmetico de una llamada a una funcion javascript que no existe, lo que no impide que el formulario cumpla su función. Acabo de remover dicha llamada. Aclaro nuevamente que el error javascript NO IMPACTA negativamente en la importación de contactos via CSV.

**Comment by TadeoArmenta** [comment]
Muchas gracias,  quizas entonces no estoy hqciendo bien los csv, por que no me importa nada, por eso fue que revise la consola en primer lugar.

Phone,name,email
1111111111,nombre,un@email

Csv, delimitado por comas, utf8 con ese formato
Que me falta?

**Comment by asternic** [comment]
Hola Tadeo, revisaste si la tabla calls tiene registros luego de la importación? Quizás *si* que está importando, la cosa es que es dificil de determinar:

mysql -u root -p call_center -e "select * from calls"

El CSV que yo use para pruebas fue con solo dos campos:

,Nombre
609123,"Nicolas"
123123,"Tadeo"

**Comment by TadeoArmenta** [comment]
En efecto, si esta importando, no sabia que tabla era la que guardaba los datos, despues de tu ultimo comentario revise y en la tabla si aparecian los datos.

Retomando:

El problema original era que nunca le aparecina los numeros para llamar alos agentes, entonses desde la pagina de "campañas" le pique en el link que descarga el cvs guradado(asumiendo quiza erroneamente que ese link devuelve los mismos datos que yo habia subido anteriormente), y lo que me da es un csv vacio; por eso me fue a checar el proceso de carga de datos y fue cuando note la falta de la funcion de js.

por recomendaciones del foro, borre todo y vovi a instalar un par de veces desde cero, con los mismos resultados.
para ello use el iso:

 issabel4-USB-DVD-x86_64-20170714.iso

El Sabado pasado, note que habian subido el iso RC asi que lo descargue, eh instale con la opcion de asterisk 13, y es el que tengo actualmente instalado, solo que ahora no puedo ver si los datos que ya confirmamos que si estan en la base de datos se cargan en la sesion de los agentes, por que me sucede que se cuelga la llamada antes de hacer el login.

voi a formatear e instalar el RC xon asterisk 11, para descartar que ssea por ahi el asunto de los cuelgues, si paso de ahi checo lo de la carga de campaña y te comento.

Muchisimas gracias, tenme un poquito de paciencia, soy desarrollador y pretendo ayudar, solo que tengo muy oxidado el php, ya tengo años trabajando en django y nodejs, pero nomas agarre ritmo pretendo ayudar en lo que pueda.

saludos.

**Comment by TadeoArmenta** [comment]
Hice lo que te comente, instale con asterisk 11, y otravez puedo loguear mis agentes, siguen sin parecerles llamadas, pero creo que es configuracion de mi trunk

seguire revisando, pero dime en que repo pudiera abrir el issue de asterisk13?

**Comment by asternic** [comment]
Has agregado a tus agentes como miembros de cola en la configuración de dichas colas (A1000,A1001, etc)? Si no estan definidos los miembros de cola, la campaña saliente no enviará llamados. (No basta con crearlos en los menúes de call center, hay que agregarlos en la cola en si).

Con respecto a Asterisk13, puedes reportar aquí mismo. El futuro del modulo de call con asterisk mas nuevos se ve complejo, ya que chan_agent ha sido deprecado y tendra que ser reemplazado.

**Comment by TadeoArmenta** [comment]
https://jroliva.net/howto-elastix-callcenter-%C2%A8la-guia-total%C2%A8/

eh seguido ese tutorial, o versiones de es mismo que hay en youtube, pero definitivamente es problema con mi trunk, ando buscando donde debuguear la conexion el provedor....

**Comment by asternic** [comment]
Habilita el asterisk full debug , incrementa verbose y debug desde consola y luego mira el /var/log/asterisk/full por pistas sobre el fallo.
